#!/usr/bin/env python3
"""Generate development-only Emerald Isle resource scenarios.

The generated XML is staged only by tools/stage-dev-mod.sh. It is not committed
as runtime content and is never copied by tools/stage-mod.sh.
"""

from __future__ import annotations

import argparse
import html
import sys
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from pathlib import Path


COMMON_RESOURCES: dict[str, int] = {
    "WoodLog": 1000,
    "Steel": 1000,
    "ComponentIndustrial": 100,
    "BlocksGranite": 500,
    "BlocksLimestone": 500,
    "BlocksSandstone": 500,
    "BlocksSlate": 500,
    "BlocksMarble": 500,
    "MealSimple": 100,
    "MedicineIndustrial": 100,
    "Silver": 5000,
}

DEFAULT_EMERALD_ISLE_ITEM_COUNT = 250


@dataclass(frozen=True)
class Resource:
    def_name: str
    count: int
    source: str


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate the Emerald Isle developer resource scenario."
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="Repository root. Defaults to the parent of tools/.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help=(
            "Output XML path. Defaults to "
            "build/dev-generated/Defs/ScenarioDefs/EI_Dev_AutoResources.generated.xml."
        ),
    )
    return parser.parse_args()


def read_xml(path: Path) -> ET.Element:
    try:
        return ET.parse(path).getroot()
    except ET.ParseError as exc:
        raise SystemExit(f"Invalid XML in {path}: {exc}") from exc


def discover_emerald_isle_items(repo_root: Path) -> list[Resource]:
    resources: list[Resource] = []
    items_root = repo_root / "Defs" / "ThingDefs_Items"

    if not items_root.is_dir():
        return resources

    for xml_path in sorted(items_root.rglob("*.xml")):
        root = read_xml(xml_path)
        for thing_def in root.iter("ThingDef"):
            def_name_element = thing_def.find("defName")
            if def_name_element is None or not def_name_element.text:
                continue

            def_name = def_name_element.text.strip()
            if not def_name.startswith("EI_"):
                continue

            resources.append(
                Resource(
                    def_name=def_name,
                    count=DEFAULT_EMERALD_ISLE_ITEM_COUNT,
                    source=str(xml_path.relative_to(repo_root)),
                )
            )

    return resources


def read_feature_test_packs(repo_root: Path) -> list[Resource]:
    resources: list[Resource] = []
    packs_root = repo_root / "Dev" / "TestPacks"

    if not packs_root.is_dir():
        return resources

    for xml_path in sorted(packs_root.glob("*.xml")):
        if xml_path.name.endswith(".disabled"):
            continue

        root = read_xml(xml_path)
        if root.tag != "DeveloperTestPack":
            raise SystemExit(
                f"{xml_path} must have <DeveloperTestPack> as the document root."
            )

        resources_element = root.find("resources")
        if resources_element is None:
            continue

        for item in resources_element.findall("li"):
            def_name = (item.get("defName") or "").strip()
            count_text = (item.get("count") or "").strip()

            if not def_name:
                raise SystemExit(f"{xml_path}: resource entry is missing defName.")

            try:
                count = int(count_text)
            except ValueError as exc:
                raise SystemExit(
                    f"{xml_path}: resource {def_name} has invalid count {count_text!r}."
                ) from exc

            if count <= 0:
                raise SystemExit(
                    f"{xml_path}: resource {def_name} count must be positive."
                )

            resources.append(
                Resource(
                    def_name=def_name,
                    count=count,
                    source=str(xml_path.relative_to(repo_root)),
                )
            )

    return resources


def merge_resources(resources: list[Resource]) -> list[Resource]:
    merged: dict[str, Resource] = {}

    for resource in resources:
        existing = merged.get(resource.def_name)
        if existing is None or resource.count > existing.count:
            merged[resource.def_name] = resource

    return [merged[def_name] for def_name in sorted(merged)]


def render_scenario(resources: list[Resource]) -> str:
    lines: list[str] = [
        '<?xml version="1.0" encoding="utf-8"?>',
        "<Defs>",
        "  <!-- Generated by tools/generate-dev-resources.py. Do not edit by hand. -->",
        "  <ScenarioDef ParentName=\"ScenarioBase\">",
        "    <defName>EI_Dev_AutoResources</defName>",
        "    <label>EI dev: generated resources</label>",
        (
            "    <description>Development-only Emerald Isle scenario generated "
            "from common resources, Emerald Isle item definitions, and optional "
            "feature test packs.</description>"
        ),
        "    <scenario>",
        (
            "      <summary>Fast-start scenario with broad vanilla development "
            "resources and all discovered Emerald Isle item resources.</summary>"
        ),
        "      <parts>",
        "        <li Class=\"ScenPart_ConfigPage_ConfigureStartingPawns\">",
        "          <def>ConfigPage_ConfigureStartingPawns</def>",
        "          <pawnCount>3</pawnCount>",
        "          <pawnChoiceCount>8</pawnChoiceCount>",
        "        </li>",
        "        <li Class=\"ScenPart_PlayerPawnsArriveMethod\">",
        "          <def>PlayerPawnsArriveMethod</def>",
        "          <method>Standing</method>",
        "          <visible>false</visible>",
        "        </li>",
    ]

    for resource in resources:
        lines.extend(
            [
                f"        <!-- {html.escape(resource.source)} -->",
                "        <li Class=\"ScenPart_StartingThing_Defined\">",
                "          <def>StartingThing_Defined</def>",
                f"          <thingDef>{html.escape(resource.def_name)}</thingDef>",
                f"          <count>{resource.count}</count>",
                "        </li>",
            ]
        )

    lines.extend(
        [
            "      </parts>",
            "    </scenario>",
            "  </ScenarioDef>",
            "</Defs>",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    args = parse_args()
    repo_root = args.repo_root.resolve()
    output = args.output

    if output is None:
        output = (
            repo_root
            / "build"
            / "dev-generated"
            / "Defs"
            / "ScenarioDefs"
            / "EI_Dev_AutoResources.generated.xml"
        )
    else:
        output = output.resolve()

    resources = [
        Resource(def_name=def_name, count=count, source="built-in common resources")
        for def_name, count in COMMON_RESOURCES.items()
    ]
    resources.extend(discover_emerald_isle_items(repo_root))
    resources.extend(read_feature_test_packs(repo_root))

    merged = merge_resources(resources)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_scenario(merged), encoding="utf-8")

    print(f"Generated {output}")
    print(f"Resource entries: {len(merged)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
